import type { PricingCategoryInterface } from '../types'

export const pricingCategories: PricingCategoryInterface[] = [
  {
    id: 'customer',
    name: 'Customer',
    description: 'Professional websites for your business',
    icon: 'mdi:account-outline',
    plans: [
      {
        id: 'customer-starter',
        name: 'Starter',
        monthlyPrice: 49,
        oneTimePrice: 235,
        currency: '$',
        description: 'Perfect for personal brands',
        icon: 'mdi:rocket-launch-outline',
        monthlyLink: 'https://buy.stripe.com/4gM3cxgwledbayVgAhf3a0a',
        oneTimeLink: 'https://buy.stripe.com/00wcN7gwlfhffTf4Rzf3a0j',
        features: [
          { text: '1-Page Website', included: true },
          { text: 'Mobile Responsive', included: true },
          { text: 'Contact Form', included: true },
          { text: 'SEO Basics', included: true },
          { text: '5-Day Delivery', included: true, highlight: true },
          { text: '7-Day Revisions', included: true },
        ],
      },
      {
        id: 'customer-professional',
        name: 'Professional',
        monthlyPrice: 99,
        oneTimePrice: 475,
        currency: '$',
        description: 'Grow your business online',
        icon: 'mdi:trending-up',
        monthlyLink: 'https://buy.stripe.com/7sY3cxdk97ONePb4Rzf3a02',
        oneTimeLink: 'https://buy.stripe.com/cNi6oJa7X2ut8qN97Pf3a0k',
        popular: true,
        features: [
          { text: 'Up to 5 Pages', included: true, highlight: true },
          { text: 'Custom Design', included: true, highlight: true },
          { text: 'Blog Integration', included: true },
          { text: 'Google Analytics', included: true },
          { text: '10-Day Delivery', included: true },
          { text: '14-Day Revisions', included: true, highlight: true },
        ],
      },
      {
        id: 'customer-enterprise',
        name: 'Enterprise',
        monthlyPrice: 199,
        oneTimePrice: 955,
        currency: '$',
        description: 'Complete digital solution',
        icon: 'mdi:domain',
        monthlyLink: 'https://buy.stripe.com/28E9AVeod7ON8qN4Rzf3a04',
        oneTimeLink: 'https://buy.stripe.com/cNi28t1Br2ut36t0Bjf3a0l',
        features: [
          { text: 'Up to 10 Pages', included: true, highlight: true },
          { text: 'Advanced Animations', included: true },
          { text: 'CMS Dashboard', included: true, highlight: true },
          { text: 'Multi-language', included: true },
          { text: '14-Day Delivery', included: true },
          { text: '30-Day Revisions', included: true, highlight: true },
        ],
      },
    ],
  },
  {
    id: 'programmer',
    name: 'Programmer',
    description: 'Custom module development & support',
    icon: 'mdi:code-tags',
    plans: [
      {
        id: 'programmer-single',
        name: 'Single',
        monthlyPrice: 79,
        oneTimePrice: 379,
        currency: '$',
        description: 'Build your own projects',
        icon: 'mdi:laptop',
        monthlyLink: 'https://buy.stripe.com/cNi14p93T8SRcH3abTf3a06',
        oneTimeLink: 'https://buy.stripe.com/fZu6oJ93T0ml22pck1f3a0m',
        features: [
          { text: 'All Modules (Open Source)', included: true },
          { text: '1 Custom Module', included: true, highlight: true },
          { text: 'Full Source Code Access', included: true },
          { text: 'Git Repo with CI/CD', included: true },
          { text: 'Module Documentation', included: true },
          { text: 'Community Discord', included: true },
        ],
      },
      {
        id: 'programmer-team',
        name: 'Team',
        monthlyPrice: 149,
        oneTimePrice: 715,
        currency: '$',
        description: 'For dev teams & startups',
        icon: 'mdi:account-group',
        monthlyLink: 'https://buy.stripe.com/6oU00l2Fv5GF7mJbfXf3a08',
        oneTimeLink: 'https://buy.stripe.com/9B600l7ZP6KJfTf2Jrf3a0n',
        popular: true,
        features: [
          { text: 'All Modules (Open Source)', included: true },
          { text: '2 Custom Modules', included: true, highlight: true },
          { text: 'Priority Bug Fixes', included: true, highlight: true },
          { text: 'API Docs (OpenAPI)', included: true },
          { text: 'Unit & E2E Tests', included: true },
          { text: 'Code Review Session', included: true },
        ],
      },
      {
        id: 'programmer-agency',
        name: 'Agency',
        monthlyPrice: 299,
        oneTimePrice: 1435,
        currency: '$',
        description: 'Scale your agency',
        icon: 'mdi:office-building',
        monthlyLink: 'https://buy.stripe.com/9B6fZj93T4CB4axbfXf3a0b',
        oneTimeLink: 'https://buy.stripe.com/fZufZj6VLfhfayV3Nvf3a0o',
        features: [
          { text: 'All Modules (Open Source)', included: true },
          { text: '4 Custom Modules', included: true, highlight: true },
          { text: 'Unlimited Revisions', included: true, highlight: true },
          { text: 'Architecture Consulting', included: true },
          { text: 'Custom CLI Tools', included: true },
          { text: 'Priority Support (24h)', included: true },
        ],
      },
    ],
  },
  {
    id: 'entrepreneur',
    name: 'Entrepreneur',
    description: 'Launch your digital product',
    icon: 'mdi:briefcase-outline',
    plans: [
      {
        id: 'entrepreneur-launch',
        name: 'Launch',
        monthlyPrice: 299,
        oneTimePrice: 1435,
        currency: '$',
        description: 'Validate your idea fast',
        icon: 'mdi:lightbulb-outline',
        monthlyLink: 'https://buy.stripe.com/7sYdRbcg56KJ5eBbfXf3a0d',
        oneTimeLink: 'https://buy.stripe.com/5kQeVfgwld97bCZbfXf3a0p',
        features: [
          { text: 'Launch-Ready MVP', included: true, highlight: true },
          { text: 'Login & Registration', included: true },
          { text: 'Admin Panel', included: true },
          { text: 'Mobile Responsive', included: true },
          { text: '2-Week Delivery', included: true, highlight: true },
          { text: 'Free Hosting Setup', included: true },
        ],
      },
      {
        id: 'entrepreneur-growth',
        name: 'Growth',
        monthlyPrice: 499,
        oneTimePrice: 2395,
        currency: '$',
        description: 'Scale with confidence',
        icon: 'mdi:chart-line',
        monthlyLink: 'https://buy.stripe.com/4gMbJ3dk97ONdL75VDf3a0f',
        oneTimeLink: 'https://buy.stripe.com/dRm5kF4NDedbdL797Pf3a0q',
        popular: true,
        features: [
          { text: 'SaaS-Ready Platform', included: true, highlight: true },
          { text: 'Stripe Payments', included: true, highlight: true },
          { text: 'User Subscriptions', included: true },
          { text: 'Real-Time Analytics', included: true },
          { text: 'Email Notifications', included: true },
          { text: '30-Day Support', included: true, highlight: true },
        ],
      },
      {
        id: 'entrepreneur-scale',
        name: 'Scale',
        monthlyPrice: 999,
        oneTimePrice: 4795,
        currency: '$',
        description: 'Enterprise-grade platform',
        icon: 'mdi:rocket',
        monthlyLink: 'https://buy.stripe.com/8x2bJ36VL5GFePb3Nvf3a0h',
        oneTimeLink: 'https://buy.stripe.com/eVqaEZcg56KJ7mJdo5f3a0r',
        features: [
          {
            text: 'Multi-Tenant Architecture',
            included: true,
            highlight: true,
          },
          { text: 'Advanced API System', included: true },
          { text: 'Role-Based Access', included: true },
          { text: 'Webhooks & Integrations', included: true },
          { text: 'White-Label Ready', included: true, highlight: true },
          { text: '90-Day Priority Support', included: true, highlight: true },
        ],
      },
    ],
  },
]
