import type { PricingCategoryInterface } from '../types'

export const pricingCategories: PricingCategoryInterface[] = [
  {
    id: 'customer',
    name: 'Customer',
    description: 'Professional websites for your business',
    icon: 'mdi:account-outline',
    plans: [
      {
        id: 'customer-starter',
        name: 'Starter',
        monthlyPrice: 49,
        oneTimePrice: 235,
        currency: '$',
        description: 'Perfect for personal brands',
        icon: 'mdi:rocket-launch-outline',
        monthlyLink: 'https://buy.stripe.com/4gM3cxgwledbayVgAhf3a0a',
        oneTimeLink: 'https://buy.stripe.com/00wcN7gwlfhffTf4Rzf3a0j',
        features: [
          { text: '1-page website', included: true, highlight: true },
          { text: '+ 2 custom modules', included: true, highlight: true },
          { text: 'Advanced animations', included: true },
          { text: 'Mobile responsive', included: true },
          { text: 'Contact form', included: true },
          { text: 'Basic SEO', included: true },
          { text: '5-day delivery', included: true, highlight: true },
          { text: '7-day revisions', included: true },
        ],
      },
      {
        id: 'customer-professional',
        name: 'Professional',
        monthlyPrice: 99,
        oneTimePrice: 475,
        currency: '$',
        description: 'Grow your business online',
        icon: 'mdi:trending-up',
        monthlyLink: 'https://buy.stripe.com/7sY3cxdk97ONePb4Rzf3a02',
        oneTimeLink: 'https://buy.stripe.com/cNi6oJa7X2ut8qN97Pf3a0k',
        popular: true,
        features: [
          { text: '+ up to 5 pages total', included: true, highlight: true },
          { text: '+ 2 custom modules', included: true, highlight: true },
          { text: 'CMS dashboard', included: true, highlight: true },
          { text: 'Blog integration', included: true },
          { text: 'Google Analytics', included: true },
          { text: '10-day delivery', included: true },
          { text: '14-day revisions', included: true, highlight: true },
        ],
      },
      {
        id: 'customer-enterprise',
        name: 'Enterprise',
        monthlyPrice: 199,
        oneTimePrice: 955,
        currency: '$',
        description: 'Complete digital solution',
        icon: 'mdi:domain',
        monthlyLink: 'https://buy.stripe.com/28E9AVeod7ON8qN4Rzf3a04',
        oneTimeLink: 'https://buy.stripe.com/cNi28t1Br2ut36t0Bjf3a0l',
        features: [
          { text: '+ up to 10 pages total', included: true, highlight: true },
          { text: '+ 3 custom modules', included: true, highlight: true },
          { text: 'Multi-language support', included: true },
          { text: 'Performance optimization', included: true },
          { text: 'Advanced SEO setup', included: true },
          { text: '30-day revisions', included: true, highlight: true },
        ],
      },
    ],
  },

  {
    id: 'programmer',
    name: 'Programmer',
    description: 'Custom module development & support',
    icon: 'mdi:code-tags',
    plans: [
      {
        id: 'programmer-single',
        name: 'Single',
        monthlyPrice: 79,
        oneTimePrice: 379,
        currency: '$',
        description: 'For solo developers',
        icon: 'mdi:laptop',
        monthlyLink: 'https://buy.stripe.com/cNi14p93T8SRcH3abTf3a06',
        oneTimeLink: 'https://buy.stripe.com/fZu6oJ93T0ml22pck1f3a0m',
        features: [
          { text: '3 custom modules', included: true, highlight: true },
          { text: 'Free 1 paid module', included: true, highlight: true },
          { text: 'Priority bug fixes', included: true },
          { text: 'Dockerized environment', included: true },
          { text: 'Database migrations', included: true },
          { text: 'Environment-based config', included: true },
          { text: 'API docs (OpenAPI)', included: true },
          { text: 'Unit & E2E tests', included: true },
          { text: 'Git repo with CI/CD', included: true },
        ],
      },
      {
        id: 'programmer-team',
        name: 'Team',
        monthlyPrice: 149,
        oneTimePrice: 715,
        currency: '$',
        description: 'For dev teams & startups',
        icon: 'mdi:account-group',
        monthlyLink: 'https://buy.stripe.com/6oU00l2Fv5GF7mJbfXf3a08',
        oneTimeLink: 'https://buy.stripe.com/9B600l7ZP6KJfTf2Jrf3a0n',
        popular: true,
        features: [
          {
            text: '+3 custom modules (6 total)',
            included: true,
            highlight: true,
          },
          {
            text: '+ free 3 paid modules (4 total)',
            included: true,
            highlight: true,
          },
          { text: 'Same-day bug fixes', included: true },
          { text: 'Preview environments per PR', included: true },
          { text: 'CI/CD with staging & production', included: true },
        ],
      },
      {
        id: 'programmer-agency',
        name: 'Agency',
        monthlyPrice: 299,
        oneTimePrice: 1435,
        currency: '$',
        description: 'For agencies & studios',
        icon: 'mdi:office-building',
        monthlyLink: 'https://buy.stripe.com/9B6fZj93T4CB4axbfXf3a0b',
        oneTimeLink: 'https://buy.stripe.com/fZufZj6VLfhfayV3Nvf3a0o',
        features: [
          {
            text: '+4 custom modules (10 total)',
            included: true,
            highlight: true,
          },
          {
            text: '+ free 5 paid modules (9 total)',
            included: true,
            highlight: true,
          },
          { text: 'SaaS-ready & multi-tenant architecture', included: true },
          { text: 'Custom tooling & internal CLI', included: true },
          {
            text: '24h priority support (SLA)',
            included: true,
            highlight: true,
          },
        ],
      },
    ],
  },

  {
    id: 'entrepreneur',
    name: 'Entrepreneur',
    description: 'Launch your digital product',
    icon: 'mdi:briefcase-outline',
    plans: [
      {
        id: 'entrepreneur-launch',
        name: 'Launch',
        monthlyPrice: 299,
        oneTimePrice: 1435,
        currency: '$',
        description: 'Validate your idea fast',
        icon: 'mdi:lightbulb-outline',
        monthlyLink: 'https://buy.stripe.com/7sYdRbcg56KJ5eBbfXf3a0d',
        oneTimeLink: 'https://buy.stripe.com/5kQeVfgwld97bCZbfXf3a0p',
        features: [
          { text: 'Launch-ready MVP', included: true, highlight: true },
          { text: '3 custom modules', included: true, highlight: true },
          { text: 'Free 3 paid modules', included: true, highlight: true },
          { text: 'Auth (login & registration)', included: true },
          { text: 'Admin panel', included: true },
          { text: 'Mobile responsive', included: true },
          { text: '2-week delivery', included: true, highlight: true },
          { text: 'Free hosting setup', included: true },
        ],
      },
      {
        id: 'entrepreneur-growth',
        name: 'Growth',
        monthlyPrice: 499,
        oneTimePrice: 2395,
        currency: '$',
        description: 'Scale with confidence',
        icon: 'mdi:chart-line',
        monthlyLink: 'https://buy.stripe.com/4gMbJ3dk97ONdL75VDf3a0f',
        oneTimeLink: 'https://buy.stripe.com/dRm5kF4NDedbdL797Pf3a0q',
        popular: true,
        features: [
          {
            text: '+ 3 custom modules (6 total)',
            included: true,
            highlight: true,
          },
          {
            text: '+ free 3 paid modules (6 total)',
            included: true,
            highlight: true,
          },
          {
            text: 'Stripe payments & subscriptions',
            included: true,
            highlight: true,
          },
          { text: 'User analytics & dashboards', included: true },
          { text: 'Email notifications', included: true },
          { text: '30-day support', included: true, highlight: true },
        ],
      },
      {
        id: 'entrepreneur-scale',
        name: 'Scale',
        monthlyPrice: 999,
        oneTimePrice: 4795,
        currency: '$',
        description: 'Enterprise-grade platform',
        icon: 'mdi:rocket',
        monthlyLink: 'https://buy.stripe.com/8x2bJ36VL5GFePb3Nvf3a0h',
        oneTimeLink: 'https://buy.stripe.com/eVqaEZcg56KJ7mJdo5f3a0r',
        features: [
          {
            text: '+ 4 custom modules (10 total)',
            included: true,
            highlight: true,
          },
          {
            text: '+ free 4 paid modules (10 total)',
            included: true,
            highlight: true,
          },
          {
            text: 'Multi-tenant architecture',
            included: true,
            highlight: true,
          },
          { text: 'Advanced API & integrations', included: true },
          { text: 'Role-based access control', included: true },
          { text: 'White-label ready', included: true },
          { text: '90-day priority support', included: true, highlight: true },
        ],
      },
    ],
  },
]
